Deleting invites for a user if they join from Invite or Home Controller
teamnzs/ios-trivia-game pull request #66
Opened 2016-12-05 09:10 UTC by plushysmurf3

* Joining a game on creation.
* Moving logic to decrement player count or to delete game (when you are last player) to quitgame method

2016-12-05 09:20 UTC, plushysmurf3 commented on ios-trivia-game/API/FirebaseClient.swift
> +        let path = "\(Constants.GAME_ROOM_TABLE_NAME)/\(gameRoom["id"]!)"
my mistake from an initial pr.  We created a unique id but generated another one.
This new code here will use the id passed into createGame

2016-12-05 09:20 UTC, plushysmurf3 commented on ios-trivia-game/ViewControllers/HomeViewController.swift
> +                if gameRoom.state != GameRoom.State.end && Date().timeIntervalSince(gameRoom.created_time) <= Double(Constants.REFRESH_GAME_ROOM_INTERVAL){
@zhiachong , @wassupnari we aren't clearing out stale game rooms.  What do you think of this check?

2016-12-05 09:20 UTC, plushysmurf3 commented on ios-trivia-game/Utilities.swift
> +        if (roomId != nil && hasJoined) {
by introducing hasJoined, we can account for @zhiachong 's code to decrement player count and removing games from the db only when you have truly joined the game, as opposed to quitting while creating the game.

2016-12-06 20:25 UTC, zhiachong requested changes
Some comments, generally looks good.

2016-12-06 20:25 UTC, zhiachong commented on ios-trivia-game/API/FirebaseClient.swift
> +        ref.child(path).queryOrdered(byChild: "room_id").queryEqual(toValue: roomId).observeSingleEvent(of: .value, with: { (snapshot) in
This one might be a good idea to keep as a listener? So that we can update the player count in real time. Thoughts?

2016-12-06 20:25 UTC, zhiachong commented on ios-trivia-game/API/FirebaseClient.swift
>              return FIRTransactionResult.success(withValue: data)
Is that the same as the following?

```
if let currentScore = data.value as? Int {
   data.value = currentScore + addValue 
}

return FIRTransactionResult.success(withValue: data)
```

2016-12-06 20:25 UTC, zhiachong commented on ios-trivia-game/API/FirebaseClient.swift
> +                return FIRTransactionResult.success(withValue: data)
Same thing here.

2016-12-06 20:25 UTC, zhiachong commented on ios-trivia-game/API/FirebaseClient.swift
> +         Logger.instance.log(logLevel: .info, message: "FirebaseClient: Creating \(path)")
Odd spacing

2016-12-06 20:25 UTC, zhiachong commented on ios-trivia-game/API/FirebaseClient.swift
> +        ref.child(path).queryOrdered(byChild: "guest_id").queryEqual(toValue: userId).observeSingleEvent(of: .value, with: { (snapshot) in
Can we keep this as a listener? The notification view relies on this to show the pop-up bar.

2016-12-06 20:31 UTC, plushysmurf3 commented on ios-trivia-game/API/FirebaseClient.swift
> +                return FIRTransactionResult.success(withValue: data)
fixing

2016-12-06 20:32 UTC, plushysmurf3 commented on ios-trivia-game/API/FirebaseClient.swift
>              return FIRTransactionResult.success(withValue: data)
fixing

2016-12-06 20:32 UTC, plushysmurf3 commented on ios-trivia-game/API/FirebaseClient.swift
> +         Logger.instance.log(logLevel: .info, message: "FirebaseClient: Creating \(path)")
fixing

2016-12-07 01:42 UTC, merged